export const categoryDisplayLabels: Record<string, string> = {
  admissionsSummary: "Admissions summary",
  advanceCarePlanning: "Advance care planning",
  alliedHealthLetter: "Allied health letter",
  certificate: "Certificate",
  clinicalNotes: "Clinical notes",
  clinicalPhotograph: "Clinical photograph",
  consentForm: "Consent form",
  das21: "DASS-21",
  dischargeSummary: "Discharge summary",
  ecg: "ECG",
  email: "Email",
  form: "Form",
  immunisation: "Immunisation",
  indigenousPip: "Indigenous PIP",
  letter: "Letter",
  medicalImagingReport: "Medical imaging report",
  myHealthRegistration: "My Health registration",
  newPtRegistrationForm: "New patient registration form",
  pathologyResults: "Pathology results",
  patientConsent: "Patient consent",
  recordRequest: "Record request",
  referralLetter: "Referral letter",
  workcover: "WorkCover",
  workcoverConsent: "WorkCover consent",
};
